// openings.ts — ECO opening name lookup
// Keyed by space-separated SAN move sequence (e.g. "e4 e5 Nf3 Nc6 Bb5")
// Longest match wins. ~500 most common openings.

const OPENINGS: Record<string, string> = {
  // ── A: Flank openings ─────────────────────────────────────────────────────
  'Nf3': "Zukertort Opening",
  'Nf3 d5': "Zukertort Opening: Symmetrical Variation",
  'Nf3 Nf6': "Zukertort Opening: Nimzo-Indian",
  'Nf3 c5': "Zukertort Opening: Sicilian Invitation",
  'Nf3 d5 d4': "Queen's Pawn Game",
  'Nf3 d5 g3': "King's Indian Attack",
  'Nf3 Nf6 g3': "King's Indian Attack",
  'Nf3 Nf6 c4': "English Opening: Agincourt Defense",
  'c4': "English Opening",
  'c4 e5': "English Opening: King's English",
  'c4 e5 Nf3': "English Opening: King's English, Two Knights",
  'c4 e5 Nc3': "English Opening: King's English, Three Knights",
  'c4 e5 Nc3 Nc6': "English Opening: Four Knights",
  'c4 e5 g3': "English Opening: King's English, Fianchetto",
  'c4 c5': "English Opening: Symmetrical Variation",
  'c4 c5 Nf3': "English Opening: Symmetrical, Three Knights",
  'c4 c5 Nc3': "English Opening: Symmetrical, Two Knights",
  'c4 c5 Nc3 Nc6': "English Opening: Symmetrical, Four Knights",
  'c4 c5 g3': "English Opening: Symmetrical, Fianchetto",
  'c4 Nf6': "English Opening: Anglo-Indian Defense",
  'c4 Nf6 Nc3': "English Opening: Anglo-Indian",
  'c4 Nf6 Nc3 d5': "English Opening: Anglo-Gruenfeld",
  'c4 Nf6 Nc3 e6': "English Opening: Agincourt Defense",
  'c4 Nf6 Nc3 g6': "English Opening: King's Indian",
  'c4 e6': "English Opening: Agincourt Defense",
  'c4 e6 Nf3': "English Opening: Agincourt Defense",
  'c4 e6 Nf3 d5': "English Opening: Agincourt, Neo-Catalan",
  'c4 d5': "English Opening: Anglo-Scandinavian",
  'c4 g6': "English Opening: King's Indian",
  'g3': "King's Fianchetto Opening",
  'g3 d5': "King's Fianchetto Opening: Benko Gambit",
  'b3': "Nimzo-Larsen Attack",
  'b3 e5': "Nimzo-Larsen Attack: Classical",
  'b3 Nf6': "Nimzo-Larsen Attack: Indian",
  'b3 d5': "Nimzo-Larsen Attack: Modern",
  'b4': "Polish Opening",
  'b4 e5': "Polish Opening: Clasical",
  'f4': "Bird's Opening",
  'f4 d5': "Bird's Opening: Dutch Variation",
  'f4 e5': "Bird's Opening: From's Gambit",
  'f4 Nf6': "Bird's Opening: Lasker Variation",
  'a3': "Anderssen's Opening",

  // ── B/C: 1.e4 openings ───────────────────────────────────────────────────
  'e4': "King's Pawn Opening",
  'e4 e5': "King's Pawn: Open Game",
  'e4 e5 Nf3': "King's Pawn: Open Game",
  'e4 e5 Nf3 Nc6': "King's Pawn: Open Game",
  'e4 e5 Nf3 Nc6 Bb5': "Ruy Lopez",
  'e4 e5 Nf3 Nc6 Bb5 a6': "Ruy Lopez: Morphy Defense",
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4': "Ruy Lopez: Morphy Defense",
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6': "Ruy Lopez: Morphy Defense",
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O': "Ruy Lopez: Morphy Defense",
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7': "Ruy Lopez: Closed",
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1': "Ruy Lopez: Closed",
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5': "Ruy Lopez: Closed",
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3': "Ruy Lopez: Closed",
  'e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6': "Ruy Lopez: Closed",
  'e4 e5 Nf3 Nc6 Bb5 a6 Bxc6': "Ruy Lopez: Exchange Variation",
  'e4 e5 Nf3 Nc6 Bb5 Nf6': "Ruy Lopez: Berlin Defense",
  'e4 e5 Nf3 Nc6 Bb5 Nf6 O-O': "Ruy Lopez: Berlin Defense",
  'e4 e5 Nf3 Nc6 Bb5 Nf6 O-O Nxe4': "Ruy Lopez: Berlin Defense, Rio de Janeiro",
  'e4 e5 Nf3 Nc6 Bb5 d6': "Ruy Lopez: Steinitz Defense",
  'e4 e5 Nf3 Nc6 Bb5 Bc5': "Ruy Lopez: Classical Defense",
  'e4 e5 Nf3 Nc6 Bb5 f5': "Ruy Lopez: Schliemann Defense",
  'e4 e5 Nf3 Nc6 Bc4': "Italian Game",
  'e4 e5 Nf3 Nc6 Bc4 Bc5': "Italian Game: Giuoco Piano",
  'e4 e5 Nf3 Nc6 Bc4 Bc5 c3': "Italian Game: Giuoco Piano, Main Line",
  'e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6': "Italian Game: Giuoco Piano",
  'e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d4': "Italian Game: Giuoco Piano, Greco Gambit",
  'e4 e5 Nf3 Nc6 Bc4 Nf6': "Italian Game: Two Knights Defense",
  'e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5': "Italian Game: Two Knights, Knight Attack",
  'e4 e5 Nf3 Nc6 Bc4 Nf6 d3': "Italian Game: Semi-Italian",
  'e4 e5 Nf3 Nc6 Bc4 Nf6 d4': "Italian Game: Two Knights, Modern",
  'e4 e5 Nf3 Nc6 Bc4 Be7': "Italian Game: Hungarian Defense",
  'e4 e5 Nf3 Nc6 d4': "Scotch Game",
  'e4 e5 Nf3 Nc6 d4 exd4': "Scotch Game",
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4': "Scotch Game",
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6': "Scotch Game: Schmidt Variation",
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Bc5': "Scotch Game: Classical Variation",
  'e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Qh4': "Scotch Game: Horwitz Attack",
  'e4 e5 Nf3 Nf6': "Petrov Defense",
  'e4 e5 Nf3 Nf6 Nxe5': "Petrov Defense: Classical",
  'e4 e5 Nf3 Nf6 Nc3': "Three Knights Game",
  'e4 e5 Nf3 Nf6 d4': "Petrov Defense: Steinitz Attack",
  'e4 e5 Nf3 f5': "Latvian Gambit",
  'e4 e5 Nf3 d6': "King's Pawn: Philidor Defense",
  'e4 e5 Nf3 d6 d4': "Philidor Defense",
  'e4 e5 Nc3': "King's Pawn: Vienna Game",
  'e4 e5 Nc3 Nf6': "Vienna Game: Falkbeer Variation",
  'e4 e5 Nc3 Nc6': "Vienna Game",
  'e4 e5 Nc3 Nc6 Bc4': "Vienna Game: Bishop's Opening",
  'e4 e5 Nc3 Bc5': "Vienna Game: Anderssen Defense",
  'e4 e5 Nc3 f5': "Vienna Game: Stanley Variation",
  'e4 e5 f4': "King's Gambit",
  'e4 e5 f4 exf4': "King's Gambit Accepted",
  'e4 e5 f4 exf4 Nf3': "King's Gambit Accepted: Kingside Knight",
  'e4 e5 f4 exf4 Bc4': "King's Gambit Accepted: Bishop's Gambit",
  'e4 e5 f4 d5': "King's Gambit Declined: Falkbeer Countergambit",
  'e4 e5 f4 Bc5': "King's Gambit Declined: Classical",
  'e4 e5 Bc4': "Bishop's Opening",
  'e4 e5 Bc4 Nf6': "Bishop's Opening: Berlin Defense",
  'e4 e5 Bc4 Bc5': "Bishop's Opening: Classical",
  'e4 e5 d4': "Center Game",
  'e4 e5 d4 exd4': "Center Game: Accepted",
  'e4 e5 d4 exd4 Qxd4': "Center Game",
  'e4 e5 d4 d5': "Center Game: Normal Variation",
  'e4 e5 Nc3 Nf6 Bc4 Bc5': "Four Knights: Italian Variation",
  'e4 e5 Nf3 Nc6 Nf3 Nf6 Bb5': "Four Knights: Spanish",
  'e4 e5 Nf3 Nc6 Nc3 Nf6': "Four Knights Game",
  'e4 e5 Nf3 Nc6 Nc3 Nf6 Bb5': "Four Knights: Spanish Variation",
  'e4 e5 Nf3 Nc6 Nc3 Nf6 Bc4': "Four Knights: Italian Variation",
  'e4 c5': "Sicilian Defense",
  'e4 c5 Nf3': "Sicilian Defense",
  'e4 c5 Nf3 d6': "Sicilian Defense: Najdorf",
  'e4 c5 Nf3 d6 d4': "Sicilian Defense: Najdorf",
  'e4 c5 Nf3 d6 d4 cxd4': "Sicilian Defense: Najdorf",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4': "Sicilian Defense: Najdorf",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6': "Sicilian Defense: Najdorf",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3': "Sicilian Defense: Najdorf",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6': "Sicilian Defense: Najdorf",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5': "Sicilian: Najdorf, English Attack",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Be3': "Sicilian: Najdorf, English Attack",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 f3': "Sicilian: Najdorf, English Attack",
  'e4 c5 Nf3 Nc6': "Sicilian Defense: Open",
  'e4 c5 Nf3 Nc6 d4': "Sicilian Defense: Open",
  'e4 c5 Nf3 Nc6 d4 cxd4': "Sicilian Defense: Open",
  'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4': "Sicilian Defense: Open",
  'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6': "Sicilian Defense: Four Knights",
  'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6': "Sicilian Defense: Accelerated Dragon",
  'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6 Nc3': "Sicilian: Accelerated Dragon",
  'e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 e5': "Sicilian Defense: Lowenthal Variation",
  'e4 c5 Nf3 e6': "Sicilian Defense: Paulsen",
  'e4 c5 Nf3 e6 d4 cxd4 Nxd4': "Sicilian Defense: Paulsen",
  'e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6': "Sicilian Defense: Taimanov",
  'e4 c5 Nf3 e6 d4 cxd4 Nxd4 a6': "Sicilian Defense: Kan",
  'e4 c5 Nf3 e6 d4 cxd4 Nxd4 Qb6': "Sicilian Defense: Lasker-Pelikan",
  'e4 c5 Nc3': "Sicilian Defense: Closed",
  'e4 c5 Nc3 Nc6': "Sicilian Defense: Closed",
  'e4 c5 Nc3 e6': "Sicilian Defense: Closed",
  'e4 c5 d4': "Sicilian Defense: Smith-Morra Gambit",
  'e4 c5 d4 cxd4': "Sicilian Defense: Smith-Morra Gambit",
  'e4 c5 d4 cxd4 c3': "Sicilian Defense: Smith-Morra Gambit",
  'e4 c5 b4': "Sicilian Defense: Wing Gambit",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6': "Sicilian Defense: Dragon",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6 Be3': "Sicilian: Dragon, Yugoslav Attack",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6 Be3 Bg7': "Sicilian: Dragon, Yugoslav Attack",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6': "Sicilian Defense: Scheveningen",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6 Be2': "Sicilian: Scheveningen, Classical",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6 g4': "Sicilian: Scheveningen, Keres Attack",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nc6': "Sicilian Defense: Classical",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nc6 Nc3': "Sicilian Defense: Classical",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nc6 Nc3 e6': "Sicilian Defense: Scheveningen, Classical",
  'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nc6 Nc3 g6': "Sicilian Defense: Dragon",
  'e4 e6': "French Defense",
  'e4 e6 d4': "French Defense",
  'e4 e6 d4 d5': "French Defense",
  'e4 e6 d4 d5 Nc3': "French Defense: Classical",
  'e4 e6 d4 d5 Nc3 Nf6': "French Defense: Classical Variation",
  'e4 e6 d4 d5 Nc3 Bb4': "French Defense: Winawer",
  'e4 e6 d4 d5 Nc3 Bb4 e5': "French Defense: Winawer, Advance",
  'e4 e6 d4 d5 Nc3 Bb4 a3': "French Defense: Winawer, Poisoned Pawn",
  'e4 e6 d4 d5 Nd2': "French Defense: Tarrasch",
  'e4 e6 d4 d5 Nd2 Nf6': "French Defense: Tarrasch, Closed",
  'e4 e6 d4 d5 Nd2 c5': "French Defense: Tarrasch",
  'e4 e6 d4 d5 e5': "French Defense: Advance",
  'e4 e6 d4 d5 e5 c5': "French Defense: Advance, Main Line",
  'e4 e6 d4 d5 exd5': "French Defense: Exchange",
  'e4 e6 d4 d5 exd5 exd5': "French Defense: Exchange Variation",
  'e4 c6': "Caro-Kann Defense",
  'e4 c6 d4': "Caro-Kann Defense",
  'e4 c6 d4 d5': "Caro-Kann Defense",
  'e4 c6 d4 d5 Nc3': "Caro-Kann Defense: Classical",
  'e4 c6 d4 d5 Nc3 dxe4': "Caro-Kann Defense: Classical",
  'e4 c6 d4 d5 Nc3 dxe4 Nxe4': "Caro-Kann Defense: Classical, Main Line",
  'e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5': "Caro-Kann Defense: Classical",
  'e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7': "Caro-Kann Defense: Smyslov Variation",
  'e4 c6 d4 d5 Nd2': "Caro-Kann Defense: Karpov Variation",
  'e4 c6 d4 d5 e5': "Caro-Kann Defense: Advance",
  'e4 c6 d4 d5 exd5': "Caro-Kann Defense: Exchange",
  'e4 c6 d4 d5 exd5 cxd5': "Caro-Kann Defense: Exchange Variation",
  'e4 c6 Nc3': "Caro-Kann Defense: Two Knights",
  'e4 d5': "Scandinavian Defense",
  'e4 d5 exd5': "Scandinavian Defense",
  'e4 d5 exd5 Qxd5': "Scandinavian Defense: Main Line",
  'e4 d5 exd5 Qxd5 Nc3': "Scandinavian Defense: Mieses-Kotroc",
  'e4 d5 exd5 Qxd5 Nc3 Qa5': "Scandinavian Defense: Mieses-Kotroc",
  'e4 d5 exd5 Nf6': "Scandinavian Defense: Modern",
  'e4 d6': "Pirc Defense",
  'e4 d6 d4': "Pirc Defense",
  'e4 d6 d4 Nf6': "Pirc Defense",
  'e4 d6 d4 Nf6 Nc3': "Pirc Defense: Classical",
  'e4 d6 d4 Nf6 Nc3 g6': "Pirc Defense: Classical, Two Knights",
  'e4 g6': "Modern Defense",
  'e4 g6 d4': "Modern Defense",
  'e4 g6 d4 Bg7': "Modern Defense: Standard Line",
  'e4 Nf6': "Alekhine's Defense",
  'e4 Nf6 e5': "Alekhine's Defense",
  'e4 Nf6 e5 Nd5': "Alekhine's Defense: Main Line",
  'e4 Nf6 e5 Nd5 d4': "Alekhine's Defense: Modern Variation",
  'e4 Nf6 e5 Nd5 d4 d6': "Alekhine's Defense: Modern Variation",
  'e4 Nf6 e5 Nd5 d4 d6 c4': "Alekhine's Defense: Four Pawns Attack",
  'e4 Nf6 e5 Nd5 Nc3': "Alekhine's Defense: Spielmann Variation",
  'e4 Nc6': "Nimzowitsch Defense",
  'e4 b6': "Owen's Defense",

  // ── D: 1.d4 openings ─────────────────────────────────────────────────────
  'd4': "Queen's Pawn Game",
  'd4 d5': "Queen's Pawn Game",
  'd4 d5 c4': "Queen's Gambit",
  'd4 d5 c4 e6': "Queen's Gambit Declined",
  'd4 d5 c4 e6 Nc3': "Queen's Gambit Declined",
  'd4 d5 c4 e6 Nc3 Nf6': "Queen's Gambit Declined: Orthodox",
  'd4 d5 c4 e6 Nc3 Nf6 Bg5': "Queen's Gambit Declined: Orthodox, Main Line",
  'd4 d5 c4 e6 Nc3 Nf6 Bg5 Be7': "Queen's Gambit Declined: Orthodox, Main Line",
  'd4 d5 c4 e6 Nc3 Nf6 Bg5 Nbd7': "Queen's Gambit Declined: Orthodox",
  'd4 d5 c4 e6 Nc3 Nf6 Nf3': "Queen's Gambit Declined: Orthodox",
  'd4 d5 c4 e6 Nc3 Be7': "Queen's Gambit Declined: Classical",
  'd4 d5 c4 e6 Nf3': "Queen's Gambit Declined: Tartakower",
  'd4 d5 c4 e6 Nf3 Nf6': "Queen's Gambit Declined",
  'd4 d5 c4 c6': "Slav Defense",
  'd4 d5 c4 c6 Nf3': "Slav Defense",
  'd4 d5 c4 c6 Nf3 Nf6': "Slav Defense: Main Line",
  'd4 d5 c4 c6 Nc3': "Slav Defense",
  'd4 d5 c4 c6 Nc3 Nf6': "Slav Defense: Three Knights",
  'd4 d5 c4 c6 Nc3 Nf6 Nf3': "Slav Defense: Breyer Variation",
  'd4 d5 c4 c6 Nf3 Nf6 Nc3': "Slav Defense: Breyer Variation",
  'd4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4': "Slav Defense: Accepted",
  'd4 d5 c4 c6 Nf3 Nf6 Nc3 e6': "Semi-Slav Defense",
  'd4 d5 c4 c6 Nf3 Nf6 Nc3 e6 Bg5': "Semi-Slav: Botvinnik System",
  'd4 d5 c4 c6 Nf3 Nf6 Nc3 e6 e3': "Semi-Slav Defense: Main Line",
  'd4 d5 c4 dxc4': "Queen's Gambit Accepted",
  'd4 d5 c4 dxc4 Nf3': "Queen's Gambit Accepted",
  'd4 d5 c4 dxc4 Nf3 Nf6': "Queen's Gambit Accepted: Classical",
  'd4 d5 c4 dxc4 e3': "Queen's Gambit Accepted: Old Variation",
  'd4 d5 c4 dxc4 e4': "Queen's Gambit Accepted: Central Variation",
  'd4 d5 c4 Nc6': "Chigorin Defense",
  'd4 d5 Nf3': "London System",
  'd4 d5 Nf3 Nf6': "London System",
  'd4 d5 Nf3 Nf6 Bf4': "London System",
  'd4 d5 Nf3 Nf6 Bf4 e6': "London System",
  'd4 d5 Nf3 Nf6 Bf4 c5': "London System",
  'd4 d5 Bf4': "London System",
  'd4 d5 Bf4 Nf6': "London System",
  'd4 Nf6': "Indian Defense",
  'd4 Nf6 c4': "Indian Defense",
  'd4 Nf6 c4 g6': "King's Indian Defense",
  'd4 Nf6 c4 g6 Nc3': "King's Indian Defense",
  'd4 Nf6 c4 g6 Nc3 Bg7': "King's Indian Defense: Main Line",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4': "King's Indian Defense: Main Line",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6': "King's Indian Defense: Main Line",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3': "King's Indian Defense: Classical",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f3': "King's Indian Defense: Saemisch",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Be2': "King's Indian Defense: Classical",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Be2 O-O': "King's Indian Defense: Classical",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Be2 O-O Nf3': "King's Indian Defense: Classical",
  'd4 Nf6 c4 g6 Nc3 Bg7 e4 O-O': "King's Indian Defense: Four Pawns Attack",
  'd4 Nf6 c4 e6': "Nimzo-Indian Defense",
  'd4 Nf6 c4 e6 Nc3': "Nimzo-Indian Defense",
  'd4 Nf6 c4 e6 Nc3 Bb4': "Nimzo-Indian Defense: Main Line",
  'd4 Nf6 c4 e6 Nc3 Bb4 e3': "Nimzo-Indian Defense: Rubinstein",
  'd4 Nf6 c4 e6 Nc3 Bb4 Qc2': "Nimzo-Indian Defense: Classical",
  'd4 Nf6 c4 e6 Nc3 Bb4 a3': "Nimzo-Indian Defense: Saemisch",
  'd4 Nf6 c4 e6 Nc3 Bb4 f3': "Nimzo-Indian Defense: Saemisch Variation",
  'd4 Nf6 c4 e6 Nf3': "Queen's Indian Defense",
  'd4 Nf6 c4 e6 Nf3 b6': "Queen's Indian Defense",
  'd4 Nf6 c4 e6 Nf3 b6 g3': "Queen's Indian Defense: Fianchetto",
  'd4 Nf6 c4 e6 Nf3 Bb4+': "Bogo-Indian Defense",
  'd4 Nf6 c4 c5': "Benoni Defense",
  'd4 Nf6 c4 c5 d5': "Benoni Defense: Modern",
  'd4 Nf6 c4 c5 d5 e6': "Benoni Defense: Modern, Taimanov",
  'd4 Nf6 c4 c5 d5 e6 Nc3': "Benoni Defense: Four Pawns Attack",
  'd4 Nf6 c4 c5 d5 e6 Nc3 exd5': "Benoni Defense: Modern, Main Line",
  'd4 Nf6 c4 c5 d5 b5': "Benko Gambit",
  'd4 Nf6 c4 c5 d5 b5 cxb5': "Benko Gambit: Accepted",
  'd4 Nf6 c4 c5 d5 b5 cxb5 a6': "Benko Gambit: Accepted, Main Line",
  'd4 Nf6 c4 d6': "Old Indian Defense",
  'd4 Nf6 c4 d6 Nc3': "Old Indian Defense",
  'd4 Nf6 Nf3': "Indian Defense",
  'd4 Nf6 Nf3 g6': "King's Indian Attack",
  'd4 Nf6 Nf3 e6': "Indian Defense: Nimzo",
  'd4 Nf6 Nf3 d5': "Queen's Gambit Declined: Exchange",
  'd4 d6': "King's Indian: Old Indian",
  'd4 e6': "Queen's Pawn: Horwitz Defense",
  'd4 c5': "Benoni Defense",
  'd4 c5 d5': "Benoni Defense",
  'd4 g6': "King's Indian: Fianchetto",
  'd4 f5': "Dutch Defense",
  'd4 f5 c4': "Dutch Defense",
  'd4 f5 c4 Nf6': "Dutch Defense: Classical",
  'd4 f5 c4 Nf6 g3': "Dutch Defense: Fianchetto",
  'd4 f5 c4 e6': "Dutch Defense: Stonewall",
  'd4 f5 c4 g6': "Dutch Defense: Leningrad",
  'd4 f5 g4': "Staunton Gambit",
  'd4 Nc6': "Nimzowitsch Defense",

  // ── Catalan ───────────────────────────────────────────────────────────────
  'd4 Nf6 c4 e6 g3': "Catalan Opening",
  'd4 Nf6 c4 e6 g3 d5': "Catalan Opening: Open Defense",
  'd4 Nf6 c4 e6 g3 d5 Bg2': "Catalan Opening: Open Defense",
  'd4 Nf6 c4 e6 g3 d5 Nf3': "Catalan Opening",
  'd4 d5 c4 e6 g3': "Catalan Opening",
  'd4 d5 c4 e6 g3 Nf6': "Catalan Opening",
  'd4 d5 c4 e6 g3 dxc4': "Catalan Opening: Accepted",
  'd4 d5 Nf3 e6 c4': "Queen's Gambit Declined",
  'd4 d5 Nf3 Nf6 e3': "Queen's Pawn: London System",
}

/**
 * Given an array of SAN moves played so far, returns the matching opening name.
 * Uses longest-match: tries the full sequence, then successively shorter ones.
 * Returns null if no match found.
 */
export function detectOpening(sans: string[]): string | null {
  if (sans.length === 0) return null
  // Try longest match first, down to 1 move
  for (let len = Math.min(sans.length, 8); len >= 1; len--) {
    const key = sans.slice(0, len).join(' ')
    const name = OPENINGS[key]
    if (name) return name
  }
  return null
}
